### Theano convolution test

In [4]:
import numpy as np
import theano
import theano.tensor as T


In [183]:
_x = T.tensor3()
_w = T.tensor4()

x4 = _x.dimshuffle(("x", 0, 1, 2))

result = T.nnet.conv2d(x4, _w,  border_mode="valid")

f = theano.function([_x, _w], result)

In [209]:
x = np.array([
    [[3, 2, 5, 6, 7, 8],
      [5, 4, 2, 10, 8, 1],
    [1, 1, 2, 1, 1, 2]],
        
    [[1, 1, 2, 1, 1, 2],
      [1, 1, 2, 1, 1, 2],
    [1, 1, 2, 1, 1, 2]]
    ], dtype="float32")

w = np.array([
[  
        [  [4, 5, 3],
           [1, 2, 3]
        ],
        [   [1, 1, 1],
            [1, 1, 2]
        ]
             
],
[  
        [  [1, 1, 3],
           [1, 1, 2]
        ],
        [   [1, 1, 1],
            [1, 1, 2]
        ]
             
]], dtype="float32")


f(x, w)

array([[[[  70.,   93.,  132.,  123.],
         [  50.,   52.,   59.,   72.]],

        [[  43.,   48.,   57.,   75.],
         [  31.,   35.,   40.,   44.]]]])

In [151]:
for i in range(x.shape[1] - 2):
    print (x[:-1,i:i+3] * w[::-1][:,::-1]).sum(), (x[1:,i:i+3] * w[::-1][:,::-1]).sum()

94.0 93.0
125.0 156.0
166.0 192.0
193.0 153.0


In [92]:
4*4 + 5*5 + 2*3 + 2*1

49

In [105]:
x[:-1,0:0+3] * w[::-1][:,::-1])

array([[  9.,   4.,   5.],
       [ 15.,  20.,   8.]], dtype=float32)

In [116]:
w[::-1][:,::-1]

array([[[ 1.,  1.,  2.],
        [ 1.,  2.,  2.]],

       [[ 1.,  2.,  3.],
        [ 4.,  5.,  3.]]], dtype=float32)

In [132]:
a = np.linspace(1,3,3).reshape((1,3))
a.shape

'1.9.2'

In [156]:
(x[:,:3] * w[0][::-1][:,::-1])

array([[  9.,   4.,   5.],
       [ 15.,  20.,   8.]], dtype=float32)

### Parameter test

In [210]:
import gzip
import pickle
model = pickle.load(gzip.open("/home/hadoop/data/handwriting/models/kr3_weblio1_c1.model.gz"))
[p.shape for p in model]

[(32, 1, 5, 5),
 (64, 32, 4, 4),
 (128, 64, 4, 4),
 (128, 50),
 (50, 30),
 (32,),
 (64,),
 (128,)]

In [247]:
print model[-4].shape
c = 0
for col in model[-4].T:
    for v in col:
        print  
    print c
    c += 1
    

(50, 30)
-0.2592586278915405 0.3494517505168915 0.2755039036273956 -0.9377813339233398 0.2631562054157257 0.5619040131568909 0.1475029438734055 0.0797650814056396 -0.2059140056371689 0.2626255452632904 0.2421877533197403 -0.0000053459316405 -0.2713211178779602 0.4284138083457947 -0.0000000000617537 -0.0863190293312073 0.4820013344287872 -0.0713231265544891 -0.1388191729784012 -0.2685858607292175 -0.0000000000580550 -0.0000000000373653 -0.0000000001124324 0.4698903262615204 0.2643743157386780 0.1810261309146881 -0.2035579532384872 0.2359273284673691 -0.0000000000304705 0.4255084991455078 0.2668360769748688 -0.2455379217863083 0.3177952766418457 -0.0002414579794277 -0.0733941867947578 -0.0000000000355486 0.2187273651361465 -0.3890520930290222 0.5169746279716492 -0.2435250282287598 -0.2843981087207794 0.0671522542834282 0.2860073149204254 -0.2795204520225525 -0.0000000000757626 -0.3298536539077759 -0.0000000000192523 -0.5250594019889832 -0.0000000718708293 -0.0000135149221023 0
-0.0928981